### PR TITLE
add binary ops

### PR DESCRIPTION
**Pull request by hirochachacha**
Done!

### CODE REVIEW

**Comment by Ambrevar** [comment]
This looks good to me. Any comment on that?

**Comment by stevedonovan** [comment]
It seemed a little complicated at the time, but it does seem useful. As long as there isn't any performance or functional regression I think it's cool. We must then update the docs, though.

**Comment by Ambrevar** [comment]
There won't, this just adds features, it does not modify the existing code (beside some trivial O(1) ops).
Point of luar is to make it easy and straightforward to use. I think it make sense to make all operations that are available on the Go side also available on the Lua side.

**Comment by stevedonovan** [comment]
Well then we should go with it! I felt bad at the time for not acting on this PR.

**Comment by Ambrevar** [comment]
What the PR does not, however, is allowing for mixed-type operations. For instance, with `m1, m2` being a `myNumber`:

``` lua
m3 = m1 + m2 -- OK
m4 = m1 + 10 -- KO
```

I think we should allow that kind of operations. Simple rule: everything that is a number can be used in arithmetic operations. Sounds cool and simple enough?

**Comment by hirochachacha** [comment]
Sorry, I don't remember the code base. 
@Ambrevar  Probably, you know better ways to do this.
I'll close this and I leave it to you. Thanks!

**Comment by hirochachacha** [comment]
Of course, please feel free to reuse the patch if you need.

**Comment by Ambrevar** [comment]
OK, thanks.

**Pull request closed without merging**
